# 设置语言
language: node_js
# 使用 lts 版本
node_js: 
  - lts/*
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  domain: museflow.io
  skip_cleanup: true
  local_dir: docs/.vuepress/dist/
  github_token: $GH_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master
branches:
  only:
  # 只监测这个分支，一有动静就开始构建
  - dev